---
  - name: copy
    become: yes
    copy:
      src:  /root/project/artifact.tar.gz
      dest: /home/ubuntu/artifact.tar.gz 

  - name: start app
    shell: |
      cd /home/ubuntu/
      mkdir backend
      cd backend
      tar -vxzf /home/ubuntu/artifact.tar.gz
      ls
      npm install
      pm2 stop default
      pm2 start npm -- start